Repository wanted-pre-onboarding-fe-team-4/pre-onboarding-9th-2-4, pull requests merged in 2023-03, with the labels that each got.

#2 [#1] Linter 셋업, Husky 셋업
  .eslintrc
  .gitignore
  .vscode/settings.json
  package.json
  src/main.tsx
  vite.config.ts
  yarn.lock
Labels: enhancement

#6 [#5] 글로벌스타일, 테마 적용
  package.json
  src/components/commons/styles/Theme.ts
  src/main.tsx
  yarn.lock
Labels: enhancement

#10 [#9] 파일 이름 에러 수정
  src/pages/Reservations/index.tsx
  src/routes/AppRouter.tsx
Labels: bug

#8 [#7] 레이아웃 적용
  src/layouts/DefaultLayout.tsx
  src/layouts/index.ts
  src/layouts/units/Header.tsx
  src/routes/AppRouter.tsx
Labels: enhancement

#25 [#16] 상품 리스트 퍼블리싱
  src/api/api.ts
  src/api/getProductList.ts
  src/components/DetailModal.tsx
  src/components/commons/Product.tsx
  src/components/commons/ProductList.tsx
  src/components/commons/ProductSkeleton.tsx
  src/context/products.tsx
  src/context/types/products.ts
  src/dummy/travel_list.json
  src/lib/createResource.ts
  src/pages/Main/index.tsx
  src/types/ProductType.ts
  src/types/SpaceCategoryType.ts
  src/types/index.ts
Labels: enhancement

#30 [#11] vercel 새로고침 오류 수정
  vercel.json
Labels: bug

#28 [#27] title, favicon 적용
  index.html
  public/icon.svg
Labels: enhancement

#36 [#24] 지역별, 가격별 필터 기능 구현
  src/components/commons/ProductList.tsx
  src/pages/Main/Filter.tsx
  src/pages/Main/index.tsx
  src/types/FilterType.ts
  src/types/FilterValueType.ts
  src/types/index.ts
Labels: enhancement

#51 [#34] api 호출 url에서 json 파일로 변경
  public/apiMockData.json
  src/api/api.ts
  src/api/getProductList.ts
Labels: bug

#53 [#40] 장바구니 페이지 전체 상품 금액 추가
  src/components/commons/Product.tsx
  src/components/commons/Reservation.tsx
  src/context/cart.tsx
  src/pages/Reservations/index.tsx
Labels: enhancement

#54 [#18, #45] detail modal 수정 (#54)
  src/components/DetailModal.tsx
Labels: enhancement

#55 [#50] 레이아웃 내부 최대 넓이 중앙정렬 적용
  src/layouts/DefaultLayout.tsx
Labels: bug

#56 [#42, #37, #35] 제품 카드의 문제점 수정
  src/components/commons/Product.tsx
  src/components/commons/Reservation.tsx
Labels: bug, enhancement

#57 [#41] 장바구니가 비었을 때 안내 메시지 추가
  src/pages/Reservations/index.tsx
Labels: enhancement

#62 카트 내부 텍스트 사이즈 수정
  src/components/commons/TravelReserveBox.tsx
Labels: bug

#65 [#31] Readme
  README.md
Labels: documentation
